---
- hosts: 192.168.0.110
  remote_user: root
  tasks:
     - yum: name=httpd state=present
     - service: name=httpd state=started enabled=yes
     - yum: name=git state=present
     - git: repo=https://github.com/demoglot/html-samples-doctor.git dest=/var/www/html

